# Generated by Django 3.2.3 on 2021-05-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url1', models.URLField(blank=True, max_length=2048, null=True)),
                ('url2', models.URLField(blank=True, max_length=2048, null=True)),
                ('url3', models.URLField(blank=True, max_length=2048, null=True)),
                ('url4', models.URLField(blank=True, max_length=2048, null=True)),
                ('url5', models.URLField(blank=True, max_length=2048, null=True)),
            ],
        ),
    ]
