# Generated by Django 3.2.3 on 2021-05-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpages',
            name='entry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
