# Generated by Django 3.2.3 on 2021-06-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_remove_webpages_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpages',
            name='entry',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
