# Generated by Django 3.2.3 on 2021-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_webpages_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpages',
            name='entry',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
