# Generated by Django 3.2.3 on 2021-06-22 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_alter_webpages_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpages',
            name='entry',
        ),
    ]
